// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy5nmpnceifOgpRB8tCEbDGeCvm4nPCTg',
    appId: '1:320096301631:web:d2859cfcc391a9ad6afe8a',
    messagingSenderId: '320096301631',
    projectId: 'passenger-ride-app',
    authDomain: 'passenger-ride-app.firebaseapp.com',
    storageBucket: 'passenger-ride-app.firebasestorage.app',
    measurementId: 'G-4MCT98HGMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxcj9i637yS8uUEGjvwQzxLZ5AoH8zPCo',
    appId: '1:320096301631:android:9932c81d357984c46afe8a',
    messagingSenderId: '320096301631',
    projectId: 'passenger-ride-app',
    storageBucket: 'passenger-ride-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBrtvcv8nNXKJUNMvIuuT_PpwcHkJSerE',
    appId: '1:320096301631:ios:5211a24495cab7726afe8a',
    messagingSenderId: '320096301631',
    projectId: 'passenger-ride-app',
    storageBucket: 'passenger-ride-app.firebasestorage.app',
    iosBundleId: 'com.example.passengerRideApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBrtvcv8nNXKJUNMvIuuT_PpwcHkJSerE',
    appId: '1:320096301631:ios:5211a24495cab7726afe8a',
    messagingSenderId: '320096301631',
    projectId: 'passenger-ride-app',
    storageBucket: 'passenger-ride-app.firebasestorage.app',
    iosBundleId: 'com.example.passengerRideApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy5nmpnceifOgpRB8tCEbDGeCvm4nPCTg',
    appId: '1:320096301631:web:d4e1427a0429bf286afe8a',
    messagingSenderId: '320096301631',
    projectId: 'passenger-ride-app',
    authDomain: 'passenger-ride-app.firebaseapp.com',
    storageBucket: 'passenger-ride-app.firebasestorage.app',
    measurementId: 'G-22FGDCK9YS',
  );

}