// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYtXn9A1uHDu0rJG0Pudxbx2Cb4P0CoLc',
    appId: '1:850198905754:web:3758f3282ef8813ac87023',
    messagingSenderId: '850198905754',
    projectId: 'rider-ba88e',
    authDomain: 'rider-ba88e.firebaseapp.com',
    storageBucket: 'rider-ba88e.firebasestorage.app',
    measurementId: 'G-JQV19LBYCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFhmW7vV2dIm6qmvRyTHgK19pp0NWHVc0',
    appId: '1:850198905754:android:a62482f079245064c87023',
    messagingSenderId: '850198905754',
    projectId: 'rider-ba88e',
    storageBucket: 'rider-ba88e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7dXSMdNIbwZhPR8-5KP4roO6zwv6kL7s',
    appId: '1:850198905754:ios:854d045f564e1d3ac87023',
    messagingSenderId: '850198905754',
    projectId: 'rider-ba88e',
    storageBucket: 'rider-ba88e.firebasestorage.app',
    iosBundleId: 'com.example.riderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7dXSMdNIbwZhPR8-5KP4roO6zwv6kL7s',
    appId: '1:850198905754:ios:854d045f564e1d3ac87023',
    messagingSenderId: '850198905754',
    projectId: 'rider-ba88e',
    storageBucket: 'rider-ba88e.firebasestorage.app',
    iosBundleId: 'com.example.riderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYtXn9A1uHDu0rJG0Pudxbx2Cb4P0CoLc',
    appId: '1:850198905754:web:b26786e259f14f53c87023',
    messagingSenderId: '850198905754',
    projectId: 'rider-ba88e',
    authDomain: 'rider-ba88e.firebaseapp.com',
    storageBucket: 'rider-ba88e.firebasestorage.app',
    measurementId: 'G-W1TYS98MWB',
  );

}