// rider_app/lib/main.dart

import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:rider_app/firebase_options.dart'; // GENERATED by 'flutterfire configure'
import 'package:rider_app/welcome_page.dart';
import 'package:rider_app/home_page.dart';
import 'package:rider_app/pages/current_location_page.dart'; // Import
import 'package:rider_app/pages/destination_entry_page.dart'; // Import
import 'package:rider_app/pages/route_map_page.dart'; // Import (even though it's pushed by MaterialPageRoute)


void main() async {
  WidgetsFlutterBinding.ensureInitialized(); // Required for Firebase initialization
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Rider App',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
        fontFamily: 'Inter', // Ensure you have this font or remove this line
        useMaterial3: true,
      ),
      // Use a StreamBuilder to listen to authentication state changes
      home: StreamBuilder<User?>(
        stream: FirebaseAuth.instance.authStateChanges(),
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Center(child: CircularProgressIndicator()); // Show loading while checking auth state
          }
          if (snapshot.hasData) {
            // User is signed in, go to Home Page
            return const HomePage();
          }
          // User is not signed in, go to Welcome Page (which leads to Login/Signup)
          return const WelcomePage();
        },
      ),
      // Define named routes
      routes: {
        '/rider/location': (context) => const CurrentLocationPage(),
        '/rider/destination': (context) => const DestinationEntryPage(),
        // Note: RouteMapPage is typically pushed directly with arguments,
        // so it might not need a named route unless you specifically want one.
        // If CurrentLocationPage tries to push a named route to RouteMapPage,
        // you'd add it here, e.g., '/rider/map': (context) => RouteMapPage(),
        // but then you'd need to handle argument passing for named routes.
        // For now, DestinationEntryPage uses MaterialPageRoute directly for RouteMapPage.
      },
    );
  }
}
